---
version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - frontend
    - mission

  frontend:
          image: 127.0.0.1:5000/frontend
    container_name: frontend
    build: ./applicationFrontEnd

  mission:
          image: 127.0.0.1:5000/mission
    container_name: mission
    build: ./applicationMission
    depends_on:
    - target
    - weapon

  target:
          image: 127.0.0.1:5000/target
    container_name: target
    build: ./applicationTarget

  weapon:
          image: 127.0.0.1:5000/weapon
    container_name: weapon
    build: ./applicationWeapon
...
