---
version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    depends_on:
    - frontend
    - mission

  frontend:
    image: 10.132.0.5:5000/frontend:$build
    container_name: frontend
    build: ./applicationFrontEnd

  mission:
    image: 10.132.0.5:5000/mission:$build
    container_name: mission
    build: ./applicationMission
    depends_on:
    - target
    - weapon

  target:
    image: 10.132.0.5:5000/target:$build
    container_name: target
    build: ./applicationTarget

  weapon:
    image: 10.132.0.5:5000/weapon:$build
    container_name: weapon
    build: ./applicationWeapon
...
