---
version: '3.7'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
    - type: bind
      source: ./nginx/nginx.conf
      target: /etc/nginx/nginx.conf
    ports:
    - target: 80
      published: 80
      protocol: tcp
    deploy:
      replicas: 3
    depends_on:
    - frontend
    - mission

  frontend:
    image: thebartthe/frontend:$build
    container_name: frontend
    build: ./applicationFrontEnd
    deploy:
      replicas: 3

  mission:
    image: thebartthe/mission:$build
    container_name: mission
    build: ./applicationMission
    deploy:
      replicas: 3
    depends_on:
    - target
    - weapon

  target:
    image: thebartthe/target:$build
    container_name: target
    build: ./applicationTarget
    deploy:
      replicas: 3

  weapon:
    image: thebartthe/weapon:$build
    container_name: weapon
    build: ./applicationWeapon
    deploy:
      replicas: 3
...
